# version: '3.8'
# services:
#   postgres:
#     # image: postgres:13
#     build: 
#       context: .
#       dockerfile: Dockerfile
#     image: extending_airflow:latest
#     environment:
#       POSTGRES_USER: airflow
#       POSTGRES_PASSWORD: airflow
#       POSTGRES_DB: airflow

#   airflow-init:
#     image: apache/airflow:2.7.3
#     depends_on:
#       - postgres
#     environment:
#       AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
#       AIRFLOW__CORE__EXECUTOR: LocalExecutor
#       AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
#       AIRFLOW__CORE__FERNET_KEY: 08f0zw5cUPVw2N33foZtHXDAjjCk8irVJRxZAMBWMTc=
#       AIRFLOW__WEBSERVER__SECRET_KEY: Y1xvBxb_D3rPXV5P4FZLPkynqmU7PIUl0us5Ui-uusI
#     volumes:
#       - ./dags:/opt/airflow/dags
#     command: >
#       bash -c "airflow db migrate &&
#                airflow users create --username admin --password admin 
#                --firstname admin --lastname admin 
#                --role Admin --email admin@example.com"

#   scheduler:
#     image: apache/airflow:2.7.3
#     depends_on:
#       - postgres
#     environment:
#       AIRFLOW__CORE__EXECUTOR: LocalExecutor
#       AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
#       AIRFLOW__CORE__FERNET_KEY: 08f0zw5cUPVw2N33foZtHXDAjjCk8irVJRxZAMBWMTc=
#       AIRFLOW__WEBSERVER__SECRET_KEY: Y1xvBxb_D3rPXV5P4FZLPkynqmU7PIUl0us5Ui-uusI
#     volumes:
#       - ./dags:/opt/airflow/dags
#     command: scheduler

#   webserver:
#     image: apache/airflow:2.7.3
#     build: 
#       context: .
#       dockerfile: Dockerfile
#     depends_on:
#       - scheduler
#     ports:
#       - "8082:8080"
#     environment:
#       AIRFLOW__CORE__EXECUTOR: LocalExecutor
#       AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
#       AIRFLOW__CORE__FERNET_KEY: 08f0zw5cUPVw2N33foZtHXDAjjCk8irVJRxZAMBWMTc=
#       AIRFLOW__WEBSERVER__SECRET_KEY: Y1xvBxb_D3rPXV5P4FZLPkynqmU7PIUl0us5Ui-uusI
#     volumes:
#       - ./dags:/opt/airflow/dags
#     command: webserver

version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow

  airflow-init:
    build:
      context: .
      dockerfile: Dockerfile
    image: extending_airflow:latest
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: 08f0zw5cUPVw2N33foZtHXDAjjCk8irVJRxZAMBWMTc=
      AIRFLOW__WEBSERVER__SECRET_KEY: Y1xvBxb_D3rPXV5P4FZLPkynqmU7PIUl0us5Ui-uusI
    volumes:
      - ./dags:/opt/airflow/dags
    command: >
      bash -c "airflow db migrate &&
               airflow users create --username admin --password admin 
               --firstname admin --lastname admin 
               --role Admin --email admin@example.com"

  scheduler:
    image: extending_airflow:latest
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: 08f0zw5cUPVw2N33foZtHXDAjjCk8irVJRxZAMBWMTc=
      AIRFLOW__WEBSERVER__SECRET_KEY: Y1xvBxb_D3rPXV5P4FZLPkynqmU7PIUl0us5Ui-uusI
    volumes:
      - ./dags:/opt/airflow/dags
    command: scheduler

  webserver:
    image: extending_airflow:latest
    depends_on:
      - scheduler
    ports:
      - "8082:8080"
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: 08f0zw5cUPVw2N33foZtHXDAjjCk8irVJRxZAMBWMTc=
      AIRFLOW__WEBSERVER__SECRET_KEY: Y1xvBxb_D3rPXV5P4FZLPkynqmU7PIUl0us5Ui-uusI
    volumes:
      - ./dags:/opt/airflow/dags
    command: webserver
